<?php

/**
 * BaseConsumption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $cns_id
 * @property int $cns_user_id
 * @property varchar $cns_ip
 * @property datetime $cns_created_at
 * @property sfGuardUser $sfGuardUser
 * 
 * @method int         getCnsId()          Returns the current record's "cns_id" value
 * @method int         getCnsUserId()      Returns the current record's "cns_user_id" value
 * @method varchar     getCnsIp()          Returns the current record's "cns_ip" value
 * @method datetime    getCnsCreatedAt()   Returns the current record's "cns_created_at" value
 * @method sfGuardUser getSfGuardUser()    Returns the current record's "sfGuardUser" value
 * @method Consumption setCnsId()          Sets the current record's "cns_id" value
 * @method Consumption setCnsUserId()      Sets the current record's "cns_user_id" value
 * @method Consumption setCnsIp()          Sets the current record's "cns_ip" value
 * @method Consumption setCnsCreatedAt()   Sets the current record's "cns_created_at" value
 * @method Consumption setSfGuardUser()    Sets the current record's "sfGuardUser" value
 * 
 * @package    cuponspike
 * @subpackage model
 * @author     Jairo Guerra
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseConsumption extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('consumption');
        $this->hasColumn('cns_id', 'int', null, array(
             'type' => 'int',
             'primary' => true,
             ));
        $this->hasColumn('cns_user_id', 'int', null, array(
             'type' => 'int',
             'notnull' => true,
             ));
        $this->hasColumn('cns_ip', 'varchar', 11, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('cns_created_at', 'datetime', null, array(
             'type' => 'datetime',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'cns_id',
             'foreign' => 'id'));
    }
}