<?php

/**
 * AppInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AppInfoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AppInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AppInfo');
    }
}