<?php

/**
 * ConsumptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConsumptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConsumptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Consumption');
    }
}