<?php

/**
 * CuponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CuponTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CuponTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cupon');
    }
}