# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Coupons Frontend Application
    description:  Consumes coupons
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [reset.css, main.css, bootstrap.min.css, roboto.min.css, material.min.css, ripples.min.css]

  javascripts:    [jquery-1.10.2.min.js, bootstrap.min.js, ripples.min.js, material.min.js]

  has_layout:     true
  layout:         layout
